# Site
repository: Kaivanov21/Kaivanov21.github.io
favicon: images/favicon.ico

# Personal info
name: Kirill Ivanov
title: Full Stack & Mobile Developer
email: kaivanov@csd.auth.gr


# Social links
#twitter_username: 
github_username:  Kaivanov21
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: 
#linkedin_username: 
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, my name is Kirill Ivanov, I'm a student in Computer Science Department of Aristotle University Thessaloniki, Greece.
  I enjoy making clean and interactive UI that is quick and easy to use whilst also giving users an enjoyable experience.
  I have worked with a range of different languages and frameworks and I am always looking for opportunities to work
  with something new. The things that I currently have the most experience working with are:
  <mark>Javascript</mark>,
  <mark>React &amp; Redux</mark>,
  <mark>Java</mark>,
  <mark>MySQL</mark>,
  <mark>Android</mark>,
  <mark>git</mark> services.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
#more_title: When I'm Not Programming
#more_content: |
  
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
